package com.zen3515.homeassistant_mobile_ble_proxy.proxy

object EspHomeMessageType {
    const val HELLO_REQUEST = 1
    const val HELLO_RESPONSE = 2
    const val DISCONNECT_REQUEST = 5
    const val DISCONNECT_RESPONSE = 6
    const val PING_REQUEST = 7
    const val PING_RESPONSE = 8
    const val DEVICE_INFO_REQUEST = 9
    const val DEVICE_INFO_RESPONSE = 10
    const val LIST_ENTITIES_REQUEST = 11
    const val LIST_ENTITIES_DONE_RESPONSE = 19
    const val SUBSCRIBE_STATES_REQUEST = 20

    const val SUBSCRIBE_BLUETOOTH_LE_ADVERTISEMENTS_REQUEST = 66
    const val BLUETOOTH_DEVICE_REQUEST = 68
    const val BLUETOOTH_DEVICE_CONNECTION_RESPONSE = 69
    const val BLUETOOTH_GATT_GET_SERVICES_REQUEST = 70
    const val BLUETOOTH_GATT_GET_SERVICES_RESPONSE = 71
    const val BLUETOOTH_GATT_GET_SERVICES_DONE_RESPONSE = 72
    const val BLUETOOTH_GATT_READ_REQUEST = 73
    const val BLUETOOTH_GATT_READ_RESPONSE = 74
    const val BLUETOOTH_GATT_WRITE_REQUEST = 75
    const val BLUETOOTH_GATT_READ_DESCRIPTOR_REQUEST = 76
    const val BLUETOOTH_GATT_WRITE_DESCRIPTOR_REQUEST = 77
    const val BLUETOOTH_GATT_NOTIFY_REQUEST = 78
    const val BLUETOOTH_GATT_NOTIFY_DATA_RESPONSE = 79
    const val SUBSCRIBE_BLUETOOTH_CONNECTIONS_FREE_REQUEST = 80
    const val BLUETOOTH_CONNECTIONS_FREE_RESPONSE = 81
    const val BLUETOOTH_GATT_ERROR_RESPONSE = 82
    const val BLUETOOTH_GATT_WRITE_RESPONSE = 83
    const val BLUETOOTH_GATT_NOTIFY_RESPONSE = 84
    const val BLUETOOTH_DEVICE_PAIRING_RESPONSE = 85
    const val BLUETOOTH_DEVICE_UNPAIRING_RESPONSE = 86
    const val UNSUBSCRIBE_BLUETOOTH_LE_ADVERTISEMENTS_REQUEST = 87
    const val BLUETOOTH_DEVICE_CLEAR_CACHE_RESPONSE = 88
    const val BLUETOOTH_LE_RAW_ADVERTISEMENTS_RESPONSE = 93
    const val BLUETOOTH_SCANNER_STATE_RESPONSE = 126
    const val BLUETOOTH_SCANNER_SET_MODE_REQUEST = 127
}

object BluetoothProxyFeatureFlags {
    const val FEATURE_PASSIVE_SCAN = 1 shl 0
    const val FEATURE_ACTIVE_CONNECTIONS = 1 shl 1
    const val FEATURE_REMOTE_CACHING = 1 shl 2
    const val FEATURE_PAIRING = 1 shl 3
    const val FEATURE_CACHE_CLEARING = 1 shl 4
    const val FEATURE_RAW_ADVERTISEMENTS = 1 shl 5
    const val FEATURE_STATE_AND_MODE = 1 shl 6

    const val PASSIVE_FEATURE_FLAGS = FEATURE_PASSIVE_SCAN or FEATURE_RAW_ADVERTISEMENTS or FEATURE_STATE_AND_MODE
    const val ACTIVE_FEATURE_FLAGS =
        PASSIVE_FEATURE_FLAGS or
            FEATURE_ACTIVE_CONNECTIONS or
            FEATURE_REMOTE_CACHING or
            FEATURE_PAIRING or
            FEATURE_CACHE_CLEARING
}
